import Head from "next/head";
import Content from "../components/content";

export default function Gallery() {
  return (
    <div className="overflow-x-hidden bg-gray-300">
      <Head>
        <title>Ineffable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Content />
    </div>
  );
}
